services:
  pi-web:
    build: .
    container_name: pi-web
    ports:
      - "3005:3000"
    volumes:
      - /mnt/user/appdata-ssd/Pi-web/data/pi-data:/root/.pi
      - /mnt/user/appdata-ssd/Pi-web/data/pi-projects:/projects
      - /mnt/user/appdata-ssd/Pi-web/data/pi-sessions:/sessions
      - /mnt/user/appdata-ssd/Pi-web/data/pi-appdata:/app/.data
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
