services:
  pi-web:
    build: .
    container_name: pi-web
    ports:
      - "3005:3000"
      - "3006:3001"
    volumes:
      - /mnt/user/appdata-ssd/Pi-web/data/pi-data:/home/node/.pi
      - /mnt/user/appdata-ssd/Pi-web/data/pi-projects:/projects
      - /mnt/user/appdata-ssd/Pi-web/data/pi-sessions:/sessions
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
